# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_independent_imagenfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='independent',
            name='imagenFile',
            field=models.ImageField(blank=True, upload_to=b'/static/images'),
        ),
    ]
